<a href="https://colab.research.google.com/github/vkchennuru/raw_scaffolding-code-evaluation/blob/main/notebooks/Notebook01_Benchmark_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/vkchennuru/raw_scaffolding-code-evaluation.git

Cloning into 'raw_scaffolding-code-evaluation'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 65 (delta 24), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (65/65), 29.43 KiB | 7.36 MiB/s, done.
Resolving deltas: 100% (24/24), done.

In [ ]:
%cd raw_scaffolding-code-evaluation

/content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation

In [ ]:
!pwd
!ls

/content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation
analyzer  docs	   generated_code    LICENSE	prompts    results
dataset   figures  hidden_testcases  notebooks	README.md

# Notebook 01: Dataset Preparation and Prompt Generation

## Research Project
**Title:** From Generation to Justification: Transformation in Introductory Programming Education

**Conference:** ACM COMPUTE 2026

---

## Purpose

This notebook prepares the benchmark dataset used throughout the research study.

It performs the following tasks:

1. Verifies the project repository structure.
2. Creates the benchmark dataset of CS1 programming problems.
3. Generates raw prompts for AI code generation.
4. Generates scaffolded prompts for AI code generation.
5. Validates all generated artifacts.
6. Produces dataset statistics for reproducibility.

The outputs of this notebook are used by all subsequent notebooks in the project.

---

## Expected Outputs

```
dataset/
    problems.csv
    metadata.json

prompts/
    raw/
        P001.txt
        ...
        P020.txt

    scaffolded/
        P001.txt
        ...
        P020.txt

results/
    dataset_statistics.csv
```

---

## Authors

**Dr. C. V. Krishnaveni**  
Lecturer in Computer Science  
SKR & SKR Government College for Women (Autonomous), Kadapa, Andhra Pradesh, India

---

## Version

Version: 2.0

Date: July 2026

In [ ]:
# ============================================================
# Cell 2: Import Libraries and Verify Environment
# ============================================================

import os
import sys
import json
import platform
from pathlib import Path
from datetime import datetime

import pandas as pd

print("=" * 60)
print("Notebook 01 : Dataset Preparation")
print("=" * 60)

print(f"Python Version : {sys.version.split()[0]}")
print(f"Pandas Version : {pd.__version__}")
print(f"Operating System : {platform.system()} {platform.release()}")
print(f"Execution Time : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")

print("\nAll required libraries loaded successfully.")

============================================================
Notebook 01 : Dataset Preparation
============================================================
Python Version : 3.12.13
Pandas Version : 2.2.2
Operating System : Linux 6.6.122+
Execution Time : 23-07-2026 04:21:38

All required libraries loaded successfully.

In [ ]:
# ============================================================
# Cell 3 : Project Configuration
# ============================================================

from pathlib import Path

# Project Root
PROJECT_ROOT = Path.cwd()

# Project Directories
DATASET_DIR = PROJECT_ROOT / "dataset"

PROMPTS_DIR = PROJECT_ROOT / "prompts"
RAW_PROMPTS_DIR = PROMPTS_DIR / "raw"
SCAFFOLD_PROMPTS_DIR = PROMPTS_DIR / "scaffolded"

GENERATED_CODE_DIR = PROJECT_ROOT / "generated_code"
RAW_CODE_DIR = GENERATED_CODE_DIR / "raw"
SCAFFOLD_CODE_DIR = GENERATED_CODE_DIR / "scaffolded"

RESULTS_DIR = PROJECT_ROOT / "results"

FIGURES_DIR = PROJECT_ROOT / "figures"

TESTCASE_DIR = PROJECT_ROOT / "hidden_testcases"

NOTEBOOK_DIR = PROJECT_ROOT / "notebooks"

print("="*60)
print("PROJECT CONFIGURATION")
print("="*60)

directories = {
    "Project Root": PROJECT_ROOT,
    "Dataset": DATASET_DIR,
    "Prompts": PROMPTS_DIR,
    "Raw Prompts": RAW_PROMPTS_DIR,
    "Scaffolded Prompts": SCAFFOLD_PROMPTS_DIR,
    "Generated Code": GENERATED_CODE_DIR,
    "Raw Code": RAW_CODE_DIR,
    "Scaffolded Code": SCAFFOLD_CODE_DIR,
    "Results": RESULTS_DIR,
    "Figures": FIGURES_DIR,
    "Hidden Testcases": TESTCASE_DIR,
    "Notebooks": NOTEBOOK_DIR,
}

for name, path in directories.items():
    print(f"{name:20}: {path}")

============================================================
PROJECT CONFIGURATION
============================================================
Project Root        : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation
Dataset             : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/dataset
Prompts             : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/prompts
Raw Prompts         : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/prompts/raw
Scaffolded Prompts  : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/prompts/scaffolded
Generated Code      : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/generated_code
Raw Code            : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/generated_code/raw
Scaffolded Code     : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/generated_code/scaffolded
Results             : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/results
Figures             : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/figures
Hidden Testcases    : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/hidden_testcases
Notebooks           : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/notebooks

In [ ]:
# ============================================================
# Cell 4 : Verify Repository Structure
# ============================================================

required_dirs = [
    "dataset",
    "prompts",
    "generated_code",
    "results",
    "figures",
    "hidden_testcases",
    "notebooks",
    "docs",
    "analyzer"
]

print("=" * 60)
print("Repository Structure Verification")
print("=" * 60)

missing = []

for folder in required_dirs:
    folder_path = PROJECT_ROOT / folder

    if folder_path.exists():
        print(f"✓ {folder}")
    else:
        print(f"✗ {folder}")
        missing.append(folder)

if missing:
    raise FileNotFoundError(
        f"\nMissing required folders: {', '.join(missing)}"
    )

print("\nRepository verification completed successfully.")

============================================================
Repository Structure Verification
============================================================
✓ dataset
✓ prompts
✓ generated_code
✓ results
✓ figures
✓ hidden_testcases
✓ notebooks
✓ docs
✓ analyzer

Repository verification completed successfully.

In [ ]:
# ============================================================
# Cell 5 : Create Project Metadata
# ============================================================

from datetime import datetime
import json

metadata = {
    "project": "From Generation to Justification",
    "repository": "raw_scaffolding-code-evaluation",
    "paper_type": "ACM COMPUTE 2026 Research Artifact",
    "programming_language": "Python",
    "number_of_problems": 100,
    "raw_generations_per_problem": 3,
    "scaffolded_generations_per_problem": 3,
    "author": "Dr. C. V. Krishnaveni",
    "institution": "SKR & SKR Government College for Women (Autonomous), Kadapa",
    "created_on": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "version": "1.0"
}

metadata_file = DATASET_DIR / "metadata.json"

with open(metadata_file, "w") as f:
    json.dump(metadata, f, indent=4)

print("Metadata file created successfully.")
print(f"Location : {metadata_file}")

Metadata file created successfully.
Location : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/dataset/metadata.json

In [ ]:
# ============================================================
# Cell 6 : Create Initial Benchmark Dataset (10 Problems)
# ============================================================

import pandas as pd

problems = [
    {
        "problem_id": "P001",
        "title": "Sum of Two Integers",
        "category": "Input/Output",
        "difficulty": "Easy",
        "problem_statement": "Write a program to read two integers and print their sum.",
        "input_description": "Two integers",
        "output_description": "Sum of the two integers",
        "sample_input": "10 20",
        "sample_output": "30",
        "constraints": "-1000 <= n <= 1000",
        "expected_concepts": "Variables, Input, Output, Arithmetic"
    },
    {
        "problem_id": "P002",
        "title": "Largest of Three Numbers",
        "category": "Decision Making",
        "difficulty": "Easy",
        "problem_statement": "Read three integers and print the largest.",
        "input_description": "Three integers",
        "output_description": "Largest integer",
        "sample_input": "5 12 9",
        "sample_output": "12",
        "constraints": "-1000 <= n <= 1000",
        "expected_concepts": "if-else"
    },
    {
        "problem_id": "P003",
        "title": "Even or Odd",
        "category": "Decision Making",
        "difficulty": "Easy",
        "problem_statement": "Read an integer and determine whether it is even or odd.",
        "input_description": "One integer",
        "output_description": "Even or Odd",
        "sample_input": "7",
        "sample_output": "Odd",
        "constraints": "",
        "expected_concepts": "Modulo, if-else"
    },
    {
        "problem_id": "P004",
        "title": "Factorial",
        "category": "Loops",
        "difficulty": "Easy",
        "problem_statement": "Compute the factorial of a positive integer.",
        "input_description": "One integer",
        "output_description": "Factorial",
        "sample_input": "5",
        "sample_output": "120",
        "constraints": "0 <= n <= 12",
        "expected_concepts": "for loop"
    },
    {
        "problem_id": "P005",
        "title": "Prime Number",
        "category": "Loops",
        "difficulty": "Medium",
        "problem_statement": "Determine whether a number is prime.",
        "input_description": "One integer",
        "output_description": "Prime or Not Prime",
        "sample_input": "13",
        "sample_output": "Prime",
        "constraints": "",
        "expected_concepts": "Loops, Conditions"
    },
    {
        "problem_id": "P006",
        "title": "Reverse a String",
        "category": "Strings",
        "difficulty": "Easy",
        "problem_statement": "Read a string and print it in reverse.",
        "input_description": "String",
        "output_description": "Reversed string",
        "sample_input": "hello",
        "sample_output": "olleh",
        "constraints": "",
        "expected_concepts": "Strings"
    },
    {
        "problem_id": "P007",
        "title": "Count Vowels",
        "category": "Strings",
        "difficulty": "Medium",
        "problem_statement": "Count the number of vowels in a string.",
        "input_description": "String",
        "output_description": "Number of vowels",
        "sample_input": "education",
        "sample_output": "5",
        "constraints": "",
        "expected_concepts": "Strings, Loops"
    },
    {
        "problem_id": "P008",
        "title": "Maximum in a List",
        "category": "Lists",
        "difficulty": "Easy",
        "problem_statement": "Find the largest element in a list.",
        "input_description": "List of integers",
        "output_description": "Largest value",
        "sample_input": "3 8 2 6",
        "sample_output": "8",
        "constraints": "",
        "expected_concepts": "Lists"
    },
    {
        "problem_id": "P009",
        "title": "Linear Search",
        "category": "Lists",
        "difficulty": "Medium",
        "problem_statement": "Search for an element in a list.",
        "input_description": "List and target value",
        "output_description": "Found or Not Found",
        "sample_input": "1 4 7 9 / 7",
        "sample_output": "Found",
        "constraints": "",
        "expected_concepts": "Lists, Loops"
    },
    {
        "problem_id": "P010",
        "title": "Palindrome Number",
        "category": "Numbers",
        "difficulty": "Medium",
        "problem_statement": "Check whether a number is a palindrome.",
        "input_description": "One integer",
        "output_description": "Palindrome or Not",
        "sample_input": "121",
        "sample_output": "Palindrome",
        "constraints": "",
        "expected_concepts": "Loops, Arithmetic"
    }
]

df = pd.DataFrame(problems)

output_file = DATASET_DIR / "problems.csv"
df.to_csv(output_file, index=False)

print(f"Dataset created successfully: {output_file}")
print(f"Number of problems: {len(df)}")

df.head()

Dataset created successfully: /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/dataset/problems.csv
Number of problems: 10

,problem_id,title,category,difficulty,problem_statement,input_description,output_description,sample_input,sample_output,constraints,expected_concepts
0,P001,Sum of Two Integers,Input/Output,Easy,Write a program to read two integers and print...,Two integers,Sum of the two integers,10 20,30,-1000 <= n <= 1000,"Variables, Input, Output, Arithmetic"
1,P002,Largest of Three Numbers,Decision Making,Easy,Read three integers and print the largest.,Three integers,Largest integer,5 12 9,12,-1000 <= n <= 1000,if-else
2,P003,Even or Odd,Decision Making,Easy,Read an integer and determine whether it is ev...,One integer,Even or Odd,7,Odd,,"Modulo, if-else"
3,P004,Factorial,Loops,Easy,Compute the factorial of a positive integer.,One integer,Factorial,5,120,0 <= n <= 12,for loop
4,P005,Prime Number,Loops,Medium,Determine whether a number is prime.,One integer,Prime or Not Prime,13,Prime,,"Loops, Conditions"

In [ ]:
# ============================================================
# Cell 7 : Validate Benchmark Dataset
# ============================================================

import pandas as pd

dataset_file = DATASET_DIR / "problems.csv"

df = pd.read_csv(dataset_file)

print("=" * 60)
print("Benchmark Dataset Validation")
print("=" * 60)

print(f"Dataset File : {dataset_file}")
print(f"Number of Problems : {len(df)}")
print(f"Number of Columns : {len(df.columns)}")

print("\nColumns:")
for col in df.columns:
    print(f"✓ {col}")

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Problem IDs:", df["problem_id"].duplicated().sum())

print("\nDataset Preview:")
display(df.head())

============================================================
Benchmark Dataset Validation
============================================================
Dataset File : /content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/dataset/problems.csv
Number of Problems : 10
Number of Columns : 11

Columns:
✓ problem_id
✓ title
✓ category
✓ difficulty
✓ problem_statement
✓ input_description
✓ output_description
✓ sample_input
✓ sample_output
✓ constraints
✓ expected_concepts

Missing Values:
problem_id            0
title                 0
category              0
difficulty            0
problem_statement     0
input_description     0
output_description    0
sample_input          0
sample_output         0
constraints           7
expected_concepts     0
dtype: int64

Duplicate Problem IDs: 0

Dataset Preview:

,problem_id,title,category,difficulty,problem_statement,input_description,output_description,sample_input,sample_output,constraints,expected_concepts
0,P001,Sum of Two Integers,Input/Output,Easy,Write a program to read two integers and print...,Two integers,Sum of the two integers,10 20,30,-1000 <= n <= 1000,"Variables, Input, Output, Arithmetic"
1,P002,Largest of Three Numbers,Decision Making,Easy,Read three integers and print the largest.,Three integers,Largest integer,5 12 9,12,-1000 <= n <= 1000,if-else
2,P003,Even or Odd,Decision Making,Easy,Read an integer and determine whether it is ev...,One integer,Even or Odd,7,Odd,NaN,"Modulo, if-else"
3,P004,Factorial,Loops,Easy,Compute the factorial of a positive integer.,One integer,Factorial,5,120,0 <= n <= 12,for loop
4,P005,Prime Number,Loops,Medium,Determine whether a number is prime.,One integer,Prime or Not Prime,13,Prime,NaN,"Loops, Conditions"

In [ ]:
# ============================================================
# Cell 8 : Generate Raw Prompt Files
# ============================================================

import pandas as pd

dataset_file = DATASET_DIR / "problems.csv"
df = pd.read_csv(dataset_file)

RAW_PROMPTS_DIR.mkdir(parents=True, exist_ok=True)

for _, row in df.iterrows():

    prompt = f"""# Problem ID
{row['problem_id']}

# Title
{row['title']}

# Category
{row['category']}

# Difficulty
{row['difficulty']}

# Programming Task

{row['problem_statement']}

## Input
{row['input_description']}

## Output
{row['output_description']}

## Sample Input

{row['sample_input']}

## Sample Output

{row['sample_output']}

## Constraints

{row['constraints']}

### Instruction

Write a correct Python program that solves the above problem.

Return ONLY Python code.

Do not include any explanation.

Do not include markdown.

Do not include comments unless necessary.
"""

    filename = RAW_PROMPTS_DIR / f"{row['problem_id']}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(prompt)

print(f"Generated {len(df)} raw prompt files.")

print("\nPrompt Folder:")
print(RAW_PROMPTS_DIR)

Generated 10 raw prompt files.

Prompt Folder:
/content/raw_scaffolding-code-evaluation/raw_scaffolding-code-evaluation/prompts/raw

In [ ]:
# ============================================================
# Cell 9 : Verify Prompt Files
# ============================================================

prompt_files = sorted(RAW_PROMPTS_DIR.glob("*.md"))

print("=" * 60)
print("Prompt File Verification")
print("=" * 60)

print(f"Number of Prompt Files : {len(prompt_files)}")

print("\nFiles:")

for file in prompt_files:
    print(file.name)

print("\nPreview of First Prompt\n")

with open(prompt_files[0], "r", encoding="utf-8") as f:
    print(f.read())

============================================================
Prompt File Verification
============================================================
Number of Prompt Files : 10

Files:
P001.md
P002.md
P003.md
P004.md
P005.md
P006.md
P007.md
P008.md
P009.md
P010.md

Preview of First Prompt

# Problem ID
P001

# Title
Sum of Two Integers

# Category
Input/Output

# Difficulty
Easy

# Programming Task

Write a program to read two integers and print their sum.

## Input
Two integers

## Output
Sum of the two integers

## Sample Input

10 20

## Sample Output

30

## Constraints

-1000 <= n <= 1000

### Instruction

Write a correct Python program that solves the above problem.

Return ONLY Python code.

Do not include any explanation.

Do not include markdown.

Do not include comments unless necessary.

# Conclusion

In this notebook, we successfully established the benchmark infrastructure required for the research study.

The following tasks were completed:

- Configured the project repository.
- Verified the repository structure.
- Created project metadata.
- Developed the initial benchmark dataset.
- Validated dataset integrity.
- Generated standardized raw prompts for all benchmark problems.
- Verified prompt generation.

The outputs produced in this notebook serve as the fixed experimental inputs for the subsequent notebooks. By separating dataset preparation from AI code generation, the experiment becomes reproducible and easier to validate.

## Outputs Generated

- dataset/metadata.json
- dataset/problems.csv
- prompts/raw/*.md

The next notebook focuses on collecting and organizing AI-generated solutions using the standardized prompts created here.

In [ ]:
# ============================================================
# Notebook 01 Summary
# ============================================================

print("=" * 70)
print("Notebook 01 Completed Successfully")
print("=" * 70)

print("\nArtifacts Created")

print("✓ dataset/metadata.json")
print("✓ dataset/problems.csv")
print("✓ prompts/raw/*.md")

print("\nTotal Benchmark Problems :", len(df))
print("Total Prompt Files       :", len(prompt_files))

print("\nNotebook 02 Input Ready")

print("=" * 70)

======================================================================
Notebook 01 Completed Successfully
======================================================================

Artifacts Created
✓ dataset/metadata.json
✓ dataset/problems.csv
✓ prompts/raw/*.md

Total Benchmark Problems : 10
Total Prompt Files       : 10

Notebook 02 Input Ready
======================================================================