<a href="https://colab.research.google.com/github/vkchennuru/raw_scaffolding-code-evaluation/blob/main/notebooks/Notebook01_Dataset_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 01: Dataset Preparation for AI Code Evaluation

## Research Project
From Generation to Justification: Transformation in Introductory Programming Education

### Authors
Dr. C. V. Krishnaveni

---

## Aim

To create a reproducible benchmark dataset of introductory Python programming problems along with Raw AI prompts and Scaffolded AI prompts.

---

## Objectives

- Create a benchmark dataset of CS1 programming problems.
- Generate Raw AI prompts.
- Generate Scaffolded AI prompts.
- Save the dataset in CSV format.
- Create prompt files for reproducible experiments.

---

## Expected Outputs

- dataset/problems.csv
- prompts/raw/
- prompts/scaffolded/

In [ ]:
# ============================================
# Notebook 01
# Step 1: Create Project Folder Structure
# ============================================

import os

folders = [
    "dataset",
    "prompts/raw",
    "prompts/scaffolded",
    "generated_code/raw",
    "generated_code/scaffolded",
    "hidden_testcases",
    "results"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

In [ ]:
import os

for root, dirs, files in os.walk("."):
    level = root.count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")

./
    .config/
        configurations/
        logs/
            2026.06.04/
    prompts/
        raw/
        scaffolded/
    dataset/
    hidden_testcases/
    generated_code/
        raw/
        scaffolded/
    results/
    sample_data/

In [ ]:
problems = [

# ===========================
# ARRAYS
# ===========================

{
"problem_id":"P001",
"category":"Arrays",
"title":"Reverse Array",
"difficulty":"Easy",
"problem_statement":"Write a Python function to reverse a list without using built-in reverse() or slicing."
},

{
"problem_id":"P002",
"category":"Arrays",
"title":"Maximum Element",
"difficulty":"Easy",
"problem_statement":"Write a Python function to find the largest element in a list."
},

{
"problem_id":"P003",
"category":"Arrays",
"title":"Second Largest",
"difficulty":"Medium",
"problem_statement":"Write a Python function to find the second largest element in a list."
},

{
"problem_id":"P004",
"category":"Arrays",
"title":"Linear Search",
"difficulty":"Easy",
"problem_statement":"Write a Python function to search for an element in a list using linear search."
},

{
"problem_id":"P005",
"category":"Arrays",
"title":"Sum of Elements",
"difficulty":"Easy",
"problem_statement":"Write a Python function to calculate the sum of all elements in a list."
},

# ===========================
# STRINGS
# ===========================

{
"problem_id":"P006",
"category":"Strings",
"title":"Count Vowels",
"difficulty":"Easy",
"problem_statement":"Write a Python function to count the number of vowels in a string."
},

{
"problem_id":"P007",
"category":"Strings",
"title":"Palindrome",
"difficulty":"Easy",
"problem_statement":"Write a Python function to check whether a string is a palindrome."
},

{
"problem_id":"P008",
"category":"Strings",
"title":"Reverse String",
"difficulty":"Easy",
"problem_statement":"Write a Python function to reverse a string without using slicing."
},

{
"problem_id":"P009",
"category":"Strings",
"title":"Character Frequency",
"difficulty":"Medium",
"problem_statement":"Write a Python function to count the frequency of each character in a string."
},

{
"problem_id":"P010",
"category":"Strings",
"title":"Uppercase Count",
"difficulty":"Easy",
"problem_statement":"Write a Python function to count uppercase letters in a string."
},

# ===========================
# LOGIC
# ===========================

{
"problem_id":"P011",
"category":"Logic",
"title":"Prime Number",
"difficulty":"Easy",
"problem_statement":"Write a Python function to determine whether a number is prime."
},

{
"problem_id":"P012",
"category":"Logic",
"title":"Even or Odd",
"difficulty":"Easy",
"problem_statement":"Write a Python function to check whether a number is even or odd."
},

{
"problem_id":"P013",
"category":"Logic",
"title":"Leap Year",
"difficulty":"Easy",
"problem_statement":"Write a Python function to determine whether a year is a leap year."
},

{
"problem_id":"P014",
"category":"Logic",
"title":"Factorial",
"difficulty":"Easy",
"problem_statement":"Write a Python function to calculate the factorial of a number using iteration."
},

{
"problem_id":"P015",
"category":"Logic",
"title":"Fibonacci",
"difficulty":"Medium",
"problem_statement":"Write a Python function to generate the first n Fibonacci numbers."
},

# ===========================
# MATH
# ===========================

{
"problem_id":"P016",
"category":"Math",
"title":"Greatest Common Divisor",
"difficulty":"Easy",
"problem_statement":"Write a Python function to find the greatest common divisor of two numbers using the Euclidean algorithm."
},

{
"problem_id":"P017",
"category":"Math",
"title":"Least Common Multiple",
"difficulty":"Medium",
"problem_statement":"Write a Python function to calculate the least common multiple of two numbers."
},

{
"problem_id":"P018",
"category":"Math",
"title":"Sum of Digits",
"difficulty":"Easy",
"problem_statement":"Write a Python function to calculate the sum of digits of a positive integer."
},

{
"problem_id":"P019",
"category":"Math",
"title":"Armstrong Number",
"difficulty":"Medium",
"problem_statement":"Write a Python function to determine whether a number is an Armstrong number."
},

{
"problem_id":"P020",
"category":"Math",
"title":"Perfect Number",
"difficulty":"Medium",
"problem_statement":"Write a Python function to determine whether a number is a perfect number."
}

]

In [ ]:
import pandas as pd

df = pd.DataFrame(problems)

df

,problem_id,category,title,difficulty,problem_statement
0,P001,Arrays,Reverse Array,Easy,Write a Python function to reverse a list with...
1,P002,Arrays,Maximum Element,Easy,Write a Python function to find the largest el...
2,P003,Arrays,Second Largest,Medium,Write a Python function to find the second lar...
3,P004,Arrays,Linear Search,Easy,Write a Python function to search for an eleme...
4,P005,Arrays,Sum of Elements,Easy,Write a Python function to calculate the sum o...
5,P006,Strings,Count Vowels,Easy,Write a Python function to count the number of...
6,P007,Strings,Palindrome,Easy,Write a Python function to check whether a str...
7,P008,Strings,Reverse String,Easy,Write a Python function to reverse a string wi...
8,P009,Strings,Character Frequency,Medium,Write a Python function to count the frequency...
9,P010,Strings,Uppercase Count,Easy,Write a Python function to count uppercase let...
10,P011,Logic,Prime Number,Easy,Write a Python function to determine whether a...
11,P012,Logic,Even or Odd,Easy,Write a Python function to check whether a num...
12,P013,Logic,Leap Year,Easy,Write a Python function to determine whether a...
13,P014,Logic,Factorial,Easy,Write a Python function to calculate the facto...
14,P015,Logic,Fibonacci,Medium,Write a Python function to generate the first ...
15,P016,Math,Greatest Common Divisor,Easy,Write a Python function to find the greatest c...
16,P017,Math,Least Common Multiple,Medium,Write a Python function to calculate the least...
17,P018,Math,Sum of Digits,Easy,Write a Python function to calculate the sum o...
18,P019,Math,Armstrong Number,Medium,Write a Python function to determine whether a...
19,P020,Math,Perfect Number,Medium,Write a Python function to determine whether a...

In [ ]:
df.to_csv("dataset/problems.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.

In [ ]:
df2 = pd.read_csv("dataset/problems.csv")

df2

,problem_id,category,title,difficulty,problem_statement
0,P001,Arrays,Reverse Array,Easy,Write a Python function to reverse a list with...
1,P002,Arrays,Maximum Element,Easy,Write a Python function to find the largest el...
2,P003,Arrays,Second Largest,Medium,Write a Python function to find the second lar...
3,P004,Arrays,Linear Search,Easy,Write a Python function to search for an eleme...
4,P005,Arrays,Sum of Elements,Easy,Write a Python function to calculate the sum o...
5,P006,Strings,Count Vowels,Easy,Write a Python function to count the number of...
6,P007,Strings,Palindrome,Easy,Write a Python function to check whether a str...
7,P008,Strings,Reverse String,Easy,Write a Python function to reverse a string wi...
8,P009,Strings,Character Frequency,Medium,Write a Python function to count the frequency...
9,P010,Strings,Uppercase Count,Easy,Write a Python function to count uppercase let...
10,P011,Logic,Prime Number,Easy,Write a Python function to determine whether a...
11,P012,Logic,Even or Odd,Easy,Write a Python function to check whether a num...
12,P013,Logic,Leap Year,Easy,Write a Python function to determine whether a...
13,P014,Logic,Factorial,Easy,Write a Python function to calculate the facto...
14,P015,Logic,Fibonacci,Medium,Write a Python function to generate the first ...
15,P016,Math,Greatest Common Divisor,Easy,Write a Python function to find the greatest c...
16,P017,Math,Least Common Multiple,Medium,Write a Python function to calculate the least...
17,P018,Math,Sum of Digits,Easy,Write a Python function to calculate the sum o...
18,P019,Math,Armstrong Number,Medium,Write a Python function to determine whether a...
19,P020,Math,Perfect Number,Medium,Write a Python function to determine whether a...

In [ ]:
print("Total Problems :", len(df))
print()

print(df["category"].value_counts())

Total Problems : 20

category
Arrays     5
Strings    5
Logic      5
Math       5
Name: count, dtype: int64

In [ ]:
df.to_csv("dataset/problems.csv", index=False)

print("Benchmark dataset saved successfully.")

Benchmark dataset saved successfully.

In [ ]:
for index, row in df.iterrows():

    raw_prompt = row["problem_statement"]

    scaffold_prompt = f"""
Write a Python solution suitable for a first-year programming student.

Problem:
{row['problem_statement']}

Instructions:

1. Use meaningful variable names.
2. Use simple loops.
3. Avoid slicing.
4. Avoid lambda.
5. Avoid list comprehensions.
6. Add comments.
7. Explain each major step.
8. Return the solution.
"""

    with open(f"prompts/raw/{row['problem_id']}.txt","w") as f:
        f.write(raw_prompt)

    with open(f"prompts/scaffolded/{row['problem_id']}.txt","w") as f:
        f.write(scaffold_prompt)

print("Prompt files created successfully.")

Prompt files created successfully.

In [ ]:
import glob

print("Raw Prompts:", len(glob.glob("prompts/raw/*.txt")))
print("Scaffolded Prompts:", len(glob.glob("prompts/scaffolded/*.txt")))

Raw Prompts: 20
Scaffolded Prompts: 20

In [ ]:
with open("prompts/scaffolded/P001.txt","r") as f:
    print(f.read())

Write a Python solution suitable for a first-year programming student.

Problem:
Write a Python function to reverse a list without using built-in reverse() or slicing.

Instructions:

1. Use meaningful variable names.
2. Use simple loops.
3. Avoid slicing.
4. Avoid lambda.
5. Avoid list comprehensions.
6. Add comments.
7. Explain each major step.
8. Return the solution.